### ISSUE TITLE
Error("missing field `length`"} in Timestamp in TUF repository after latest update

### ISSUE THREAD

**Issue by fghanmi** [sigstore/root-signing#1372] opened 2024-09-07 10:09 UTC
**Description**

After latest update on TUF repository, the [SigstoreTrustRoot::new function](https://github.com/sigstore/sigstore-rs/blob/main/src/trust/sigstore/mod.rs#L62) in sigstore-rs is failing. The error is:

```
failed to construct SigstoreTrustRoot: TufError(ParseMetadata { role: Timestamp, source: Error("missing field `length`", line: 14, column: 4)
```

After looking at: [timestamp.json](https://tuf-repo-cdn.sigstore.dev/timestamp.json), the length field under "snapshot.json" is indeed missing. The repository was updated recently `Generated 2024-09-05T19:21+00:00`

**Comment by jku** [comment] 2024-09-07 16:11
I'll close this as a duplicate of #1251. 
* the change was intentional, and is TUF specification compliant
* unfortunately awslabs/tough, the tuf implementation that sigstore-rs uses, did not implement this correctly until a few weeks ago (and an unrelated dependency issue is preventing sigstore-rs from upgrading at the moment)

**Closed as completed by jku** 2024-09-07 16:11 UTC
Labels: bug
